name: Build SunamoCollectionsValuesTableGrid

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCollectionsValuesTableGrid
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionsValuesTableGrid/SunamoCollectionsValuesTableGrid.csproj

    - name: Build
      run: dotnet build SunamoCollectionsValuesTableGrid/SunamoCollectionsValuesTableGrid.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCollectionsValuesTableGrid.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionsValuesTableGrid.Tests/SunamoCollectionsValuesTableGrid.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCollectionsValuesTableGrid.Tests/SunamoCollectionsValuesTableGrid.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCollectionsValuesTableGrid.Tests/SunamoCollectionsValuesTableGrid.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
